# repository
repository.central.base-url=https://repo1.maven.org/maven2
repository.snapshot.base-url=https://central.sonatype.com/repository/maven-snapshots
repository.snapshot.disabled=false

# cloudflare deployment
stage.cloudflare-deployment.disabled=false
stage.cloudflare-deployment.api-token=token
stage.cloudflare-deployment.project-name=project-name
stage.cloudflare-deployment.account-id=account-id
stage.cloudflare-deployment.base-url=https://api.cloudflare.com/client/v4
stage.cloudflare-deployment.get-upload-token.endpoint=/accounts/{0}/pages/projects/{1}/upload-token
stage.cloudflare-deployment.check-missing-hashes.endpoint=/pages/assets/check-missing

stage.cloudflare-deployment.upload-assets.endpoint=/pages/assets/upload
stage.cloudflare-deployment.upload-assets.max-bucket-size-in-bytes=41943040
stage.cloudflare-deployment.upload-assets.max-bucket-file-count=1000

stage.cloudflare-deployment.upsert-hashes.endpoint=/pages/assets/upsert-hashes
stage.cloudflare-deployment.trigger-deployment.endpoint=/accounts/{0}/pages/projects/{1}/deployments

stage.cloudflare-deployment.get-deployment-status.endpoint=/accounts/{0}/pages/projects/{1}/deployments/{2}
stage.cloudflare-deployment.get-deployment-status.max-polling-attempts=5
stage.cloudflare-deployment.get-deployment-status.polling-interval-in-seconds=1

# status email
stage.status-email.disabled=false
stage.status-email.recipient=recipient@email.com
stage.status-email.sender=sender@email.com
stage.status-email.site-url=https://website.com

# temp file deletion
stage.temp-file-deletion.disabled=false

# aws credentials
aws.access-key-id=access-key-id
aws.secret-access-key=secret-access-key

# packages
package.include=in.co.akshitbansal:spring-web-query-core,in.co.akshitbansal:spring-boot-starter-web-query

# active profile
profile.active=production

# maven central
maven-central.base-url=https://central.sonatype.com
maven-central.get-deployment-status-endpoint=/api/v1/publisher/status
maven-central.username=username
maven-central.password=password

# schedule
stage.schedule.role-arn=arn
stage.schedule.lambda-arn=arn
stage.schedule.group-name=group-name