# repository
repository.central.base-url=https://repo1.maven.org/maven2
repository.snapshot.base-url=https://central.sonatype.com/repository/maven-snapshots
repository.snapshot.disabled=false

# cloudflare deployment
stage.cloudflare-deployment.disabled=false
stage.cloudflare-deployment.api-token=token
stage.cloudflare-deployment.project-name=project-name

# status email
stage.status-email.disabled=false
stage.status-email.recipient=recipient@email.com
stage.status-email.sender=sender@email.com
stage.status-email.site-url=https://website.com

# temp file deletion
stage.temp-file-deletion.disabled=false

# aws credentials
aws.access-key-id=access-key-id
aws.secret-access-key=secret-access-key

package.include=in.co.akshitbansal:spring-web-query-core,in.co.akshitbansal:spring-boot-starter-web-query