<#-- Status email template for SES (HTML). -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Javadoc Deployment Status</title>
    <style>
      body {
        margin: 0;
        padding: 0;
        background: #f7f7f4;
        color: #1c1c1c;
        font-family: "Helvetica Neue", Arial, sans-serif;
      }
      .wrap {
        max-width: 720px;
        margin: 0 auto;
        padding: 32px 20px 48px;
      }
      .card {
        background: #ffffff;
        border: 1px solid #e6e1d7;
        border-radius: 12px;
        overflow: hidden;
        box-shadow: 0 6px 22px rgba(0, 0, 0, 0.06);
      }
      .header {
        padding: 20px 24px;
        background: ${success?string("#0f3d2e", "#3f1d1d")};
        color: #ffffff;
      }
      .header h1 {
        margin: 0;
        font-size: 20px;
        letter-spacing: 0.3px;
      }
      .content {
        padding: 24px;
      }
      .status {
        display: inline-block;
        padding: 6px 12px;
        border-radius: 999px;
        font-size: 12px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.6px;
        background: ${success?string("#e6f4ef", "#f8e6e6")};
        color: ${success?string("#0f3d2e", "#7a1d1d")};
      }
      .section-title {
        margin: 24px 0 10px;
        font-size: 13px;
        text-transform: uppercase;
        letter-spacing: 0.6px;
        color: #6a6254;
      }
      ul {
        padding-left: 18px;
        margin: 8px 0 0;
      }
      li {
        margin: 4px 0;
      }
      .details {
        margin: 14px 0 0;
        padding: 10px 12px;
        background: #faf8f2;
        border: 1px solid #efe8da;
        border-radius: 8px;
        font-size: 13px;
      }
      .details div {
        margin: 4px 0;
      }
      .details span {
        color: #6a6254;
        text-transform: uppercase;
        font-size: 11px;
        letter-spacing: 0.4px;
        margin-right: 6px;
      }
      .error {
        background: #fff3f3;
        border: 1px solid #f2c5c5;
        color: #7a1d1d;
        padding: 12px;
        border-radius: 8px;
        font-family: monospace;
        font-size: 12px;
        white-space: pre-wrap;
      }
      .footer {
        margin-top: 18px;
        font-size: 12px;
        color: #8b8374;
      }
      @media (max-width: 640px) {
        .content {
          padding: 18px;
        }
      }
    </style>
  </head>
  <body>
    <div class="wrap">
      <div class="card">
        <div class="header">
          <h1>Javadoc Deployment Status</h1>
        </div>
        <div class="content">
              <span class="status">${success?string("Success", "Failure")}</span>

          <div class="details">
            <div><span>Request ID</span> ${requestId?default("N/A")}</div>
            <div><span>Site URL</span>
              <#if siteUrl?? && siteUrl?has_content>
                <a href="${siteUrl}">${siteUrl}</a>
              <#else>
                N/A
              </#if>
            </div>
          </div>

          <div class="section-title">Packages</div>
          <ul>
            <#list packages as pkg>
              <li>${pkg.groupId}:${pkg.artifactId}</li>
            </#list>
          </ul>

          <#if !success && errorMessage??>
            <div class="section-title">Error</div>
            <div class="error">${errorMessage}</div>
          </#if>

          <div class="footer">
            Generated by cloudflare-javadoc-deploy
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
